export const LOGIN = 'LOGIN'
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'

export const AUTHENTICATE = 'AUTHENTICATE'
export const AUTHENTICATE_FULFILLED = 'AUTHENTICATE_FULFILLED'
export const AUTHENTICATE_REJECTED = 'AUTHENTICATE_REJECTED'